#!/usr/bin/env node

var _ = require('lodash');


var subSchemas = require('..').subSchemas;

var data = {};

_.forOwn(subSchemas, function(schema, schemaName) {
  extractUnits(data, schemaName, schema);
})

console.log(JSON.stringify(data, null, 2));

function extractUnits(result, pathPrefix, element) {
  _.forOwn(element, function(value, key) {
    if (value.units) {
      result[pathPrefix + '.' + key] = {
        description: value.description,
        units: value.units
      };
    } else if (typeof value === 'object'){
     extractUnits(result, key === 'properties' ? pathPrefix : pathPrefix + '.' + key, value);
    }
  })
}

